_base_: '../_base_/mydataset.yml'

batch_size: 2
iters: 60000

model:
  type: MSAFormer
  backbone:
    type: MixVisionTransformer_B3
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/backbone/mix_vision_transformer_b3.tar.gz
  embedding_dim: 512
  num_classes: 3

optimizer:
  _inherited_: False
  type: AdamW
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.01

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.00006
  power: 1

loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: LovaszSoftmaxLoss
      coef: [0.35, 0.65]
  coef: [1]

